name: musiczz
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  just_audio: ^0.9.36
  file_picker: ^6.1.1
  rxdart: ^0.27.7
  # UI Enhancement packages
  google_fonts: ^6.1.0
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  lottie: ^2.7.0
  animated_text_kit: ^4.2.2
  flutter_animate: ^4.2.0
  glassmorphism: ^3.0.0
  card_swiper: ^3.0.1
  rive: ^0.12.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
